name: Ru Auto Task

on:
  schedule:
    # 每天定时执行，例如：每天的 0 点和 12 点
    - cron: '0 0,12 * * *'
  workflow_dispatch: # 支持手动触发

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Run automation script
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python main.py
